version: "{build}"

image:
  - Visual Studio 2017

configuration:
  - Release

platform: Any CPU

before_build:
  - nuget restore

build:
  parallel: true
  verbosity: minimal

build_script:
  - msbuild "GitCredentialManager.sln" /bl:GitCredentialManager.binlog /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /consoleloggerparameters:Verbosity=minimal /maxcpucount /nodeReuse:false /target:"Build" /property:Configuration="%configuration%";Platform="%platform%"

cache:
  - packages -> **\packages.config

matrix:
  fast_finish: true

test:
  assemblies:
    - '**\*.Test.dll'

artifacts:
  - path: GitCredentialManager.binlog
    name: MSBuild Log
  - path: Deploy\*.*
    name: Build Results
    type: zip

on_failure:
  - appveyor PushArtifact GitCredentialManager.binlog
